### ISSUE TITLE
Docs example uses feature in dev

### ISSUE THREAD

**Issue by Haakam21** [databento/databento-cpp#17]
[The live example on the website](https://docs.databento.com/getting-started/build-first-app?historical=cpp&live=cpp) uses PitSymbolMap, which is a helper class that exists in the dev branch but has not yet been merged to main. I suggest either reverting the docs or merging the feature.

**Comment by threecgreen** [comment]
Hi,
Thanks for bringing this to our attention. We'll be releasing a new version today with `PitSymbolMap`.
